[package]
name = "jacuzzi"
version = "0.1.0"
authors = ["William Kamp <manimaul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.2"
actix-files = "0.3.0"
lazy_static = "1.4.0"
log = "0.4.11"
env_logger = "0.7.1"
